/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tanukisoftware_wrapper_WrapperProcessOutputStream */

#ifndef _Included_org_tanukisoftware_wrapper_WrapperProcessOutputStream
#define _Included_org_tanukisoftware_wrapper_WrapperProcessOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_tanukisoftware_wrapper_WrapperProcessOutputStream
 * Method:    nativeWrite
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_tanukisoftware_wrapper_WrapperProcessOutputStream_nativeWrite
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_tanukisoftware_wrapper_WrapperProcessOutputStream
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tanukisoftware_wrapper_WrapperProcessOutputStream_nativeClose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
