/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tanukisoftware_wrapper_WrapperProcessInputStream */

#ifndef _Included_org_tanukisoftware_wrapper_WrapperProcessInputStream
#define _Included_org_tanukisoftware_wrapper_WrapperProcessInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef org_tanukisoftware_wrapper_WrapperProcessInputStream_SKIP_BUFFER_SIZE
#define org_tanukisoftware_wrapper_WrapperProcessInputStream_SKIP_BUFFER_SIZE 2048L
/* Inaccessible static: skipBuffer */
/*
 * Class:     org_tanukisoftware_wrapper_WrapperProcessInputStream
 * Method:    nativeRead
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_org_tanukisoftware_wrapper_WrapperProcessInputStream_nativeRead
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_tanukisoftware_wrapper_WrapperProcessInputStream
 * Method:    nativeClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tanukisoftware_wrapper_WrapperProcessInputStream_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     org_tanukisoftware_wrapper_WrapperProcessInputStream
 * Method:    nativeRead2
 * Signature: ([BIIZ)I
 */
JNIEXPORT jint JNICALL Java_org_tanukisoftware_wrapper_WrapperProcessInputStream_nativeRead2
  (JNIEnv *, jobject, jbyteArray, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
